### ISSUE TITLE
Function with nested type expand

### ISSUE THREAD

**Issue by rkdud007** [glihm/starknet-abigen-rs#1]
get `function` type abi as `string` and turn it's inputs and outputs into `cairo-types`
### Abi string as input
```
{
    "type": "function",
    "name": "hello_world",
    "inputs": [
      {
        "name": "value",
        "type":"core::array::Array::<core::felt252>"
      }
    ],
    "outputs": [
      {
        "type": "core::array::Array::<core::felt252>"
      }
    ],
    "state_mutability": "view"
  },
 ```
### AbiType for `core::array::Array::<core::felt252>`

```
AbiType::Nested(
            "array".to_string(),
            vec![AbiType::Nested(
                AbiType::Basic("core::felt252".to_string()),
            )],
        );
        
 ```

### CairoType as output
```
fn hello_world(value : Vec<FieldElement>) -> Vec<FieldElement> 
```
- [ ] function string -> abiType -> tokenType::FunctionToken
- [ ]  tokenType::FunctionToken -> turn into `cairo-types`

**Comment by glihm** [comment]
@rkdud007 is that ok now? Or it's something that still pending as an enhancement? :)

**Comment by rkdud007** [comment]
this is done with expand/function.rs :)
