### ISSUE TITLE
Manual generation to have the vision of expected generated code

### ISSUE THREAD

**Issue by glihm** [glihm/starknet-abigen-rs#20]
Create a folder with examples of expanded code for contracts:

- [X] Simple contract with only basic types (no struct, no enum, no array).
- [ ] ~Contract with array.~
- [X] Contract with tuples no generics.
- [X] Contract with tuples and generics.
- [X] Contract with enum only (and basics of course), with no generic.
- [X] Contract with enum and generic enums.
- [X] Contract with struct only (no generic).
- [X] Contract with struct and generic structs.

For all of these, we have to write a rust file for the expanded contract with:

```rust
// (If struct and enum)
// First, expand the types and their `CairoType` implementation as necessary.

struct ContractA {
...
}

impl ContractA {
   // Implement call and invoke using the types.
}
```

**Comment by rkdud007** [comment]
I don't think we need array expand, it's really same as `cairo-type/array.rs`
