### ISSUE TITLE
Implement u256 struct in cairo_types

### ISSUE THREAD

**Issue by glihm** [glihm/starknet-abigen-rs#3]
The `u256` struct will usually be present in ABIs. We can have it declared always in `cairo_types`. 

1. Add a struct `u256`.
2. Implement the `CairoType` trait.

**Comment by rkdud007** [comment]
https://github.com/glihm/starknet-abigen-rs/blob/a4c8a8c24467ea4f29f1241a2377b921ccce0d5c/crates/cairo-types/src/types/data_type.rs#L190-L191

Is this different from this implementation?

**Comment by rkdud007** [comment]
https://github.com/glihm/starknet-abigen-rs/blob/a4c8a8c24467ea4f29f1241a2377b921ccce0d5c/crates/abigen-macro/src/expand/struct.rs#L11

Isn't this already means, declare struct `u256` and implement `CairoType` trait? Why we need to put it in cairo_types? ( same question to #2 also)

**Comment by glihm** [comment]
The idea of having it in cairo type will avoid those very basic types defined several times.
So in your code you use `abigen!` several time, we should then ensure each generation is in a separate rust module, and also, this mean a lot's of duplicated code.

**Comment by glihm** [comment]
Actually, for `u256` you're totally right @rkdud007. It may be re-generated each time.

For `Option`, as it's an enum, we may have several implementation of options. Having it in the `cairo_types` makes it always available, for all generic types. :+1:

**Comment by glihm** [comment]
Close this as this struct will be auto-generated by `abigen` macro.
